### ISSUE TITLE
Script is not usable on a CI workflow (misses the chance to preselect terminal option)

### ISSUE THREAD

**Issue by tiagoicp** [dfinity/dfxvm#79]
Hi,

On one of my github workflows, I had the full install of dfx. Now with dfxvm it broke, since it requires an interaction:

![Screenshot 2024-03-21 at 07 48 03](https://github.com/dfinity/dfxvm/assets/19423709/8cba7083-4014-4bd0-920b-56a627ecee36)

![Screenshot 2024-03-21 at 07 47 47](https://github.com/dfinity/dfxvm/assets/19423709/34eea9c4-77f1-4526-9712-7173b01cff2b)

I tried to pipe with echo \r or yes but nothing works. Can you kindly look into this and provide a way for non-terminal use to preselect an option or just go by "default"?

Thanks 🙏

**Comment by ilbertt** [comment]
@tiagoicp have you tried using the [setup-dfx](https://github.com/dfinity/setup-dfx) GitHub action instead?
